### ISSUE TITLE
Testovani 29.11. Genie ST

### ISSUE THREAD

**Issue by jbrezmorf** [GeoMop/Genie#43]
- [x] Při chybném pokusu načíst first arrivals z tabulky s metadaty.
```
Traceback (most recent call last):
  File "/home/jb/workspace/Genie/src/genie/ui/dialogs/import_first_arrivals_dialog.py", line 191, in _handle_browse_action
    self._handle_read_action()
  File "/home/jb/workspace/Genie/src/genie/ui/dialogs/import_first_arrivals_dialog.py", line 152, in _handle_read_action
    log2 = self._find_meas()
  File "/home/jb/workspace/Genie/src/genie/ui/dialogs/import_first_arrivals_dialog.py", line 83, in _find_meas
    s_ids = [self._find_id(fa.s_x, fa.s_y, fa.s_z, tol) for fa in self.first_arrivals]
  File "/home/jb/workspace/Genie/src/genie/ui/dialogs/import_first_arrivals_dialog.py", line 83, in <listcomp>
    s_ids = [self._find_id(fa.s_x, fa.s_y, fa.s_z, tol) for fa in self.first_arrivals]
  File "/home/jb/workspace/Genie/src/genie/ui/dialogs/import_first_arrivals_dialog.py", line 119, in _find_id
    p = np.array([-abs(x), -abs(y), z])
TypeError: bad operand type for abs(): 'str'
```
... lépe ošetřit a reportovat chyby.

- [x] Při načítání tabulky s metadaty ve starém formátu:
```
....
ERROR row: 67, col: E, X is empty.
```
Ve skutečnosti je chyba ve sloupci D (value X) podle nového formátu.

- [x] Editor prvních nasazení by měl být dostupný i pomocí menu. (zatím pouze přes double click v tabulce measurements)
- [x] Otevření editoru nefunguje pro nové PyQT5. Zkoušeny 5.15.6 a 5.14.1. Hlásí:
```
Traceback (most recent call last):
  File "/home/jb/workspace/Genie/src/genie/ui/tabs/inversion_preparation.py", line 828, in _meas_view_double_click
    dlg = FirstArrivalDlg(measurement, self.genie, self)
  File "/home/jb/workspace/Genie/src/genie/ui/dialogs/first_arrival_dialog.py", line 101, in __init__
    self._create_plot()
  File "/home/jb/workspace/Genie/src/genie/ui/dialogs/first_arrival_dialog.py", line 118, in _create_plot
    checkbox = QtGui.QCheckBox()
AttributeError: module 'PyQt5.QtGui' has no attribute 'QCheckBox'
```

**Comment by jbrezmorf** [comment]
Problem s QCheckBox stejný pro PyQt5 ver 5.12.10

**Comment by radeksrb** [comment]
Hotovo.
