### ISSUE TITLE
Testovani 5.11. pokracovani

### ISSUE THREAD

**Issue by jbrezmorf** [GeoMop/Genie#7]
1. Problem s matplotlib:
```
Found locale decimal_point ',' and change it to: decimal point '.'
Traceback (most recent call last):
  File "/home/jb/workspace/Genie/src/genie/ui/tabs/inversion_preparation.py", line 631, in _handle_run_invButton
    from ..dialogs.run_inv import RunInvDlg
  File "/home/jb/workspace/Genie/src/genie/ui/dialogs/run_inv.py", line 5, in <module>
    from genie.core import ert_prepare, st_prepare
  File "/home/jb/workspace/Genie/src/genie/core/ert_prepare.py", line 3, in <module>
    import pygimli as pg
  File "/home/jb/miniconda3/lib/python3.7/site-packages/pygimli/__init__.py", line 45, in <module>
    matplotlib.use("qt5agg", warn=False)
TypeError: use() got an unexpected keyword argument 'warn'
Aborted (core dumped)
```
To je zase nejaka problematicka kompatibilita pygimli a matplotlibu. 

Tak je to nejaky deprecated paremater, snad to maji opraveno v pygimli 1.1.0 v dalsi revizi Genie bychom asi na ni meli prejit.

2. Uspesne spusteni dialogu pro inverzi, navrh zmen:
- labely udelat citelnejsi s mezerami, nemusi doslova odpovidat vnitrnim promennym
- Nastaveni meshe potrebuje vysvetleni v dokumentaci, revizi co vsechno ponechat a pripadne tooltipy.
- presun verbose do Test options, pripadne slouceni verbose a data_log
- k_ones ... jeste potreba?
- optimizeLambda vybrat automaticky

3. Instalace meshlabu? 
```
Traceback (most recent call last):
  File "/home/jb/workspace/Genie/src/genie/ui/dialogs/../../invert.py", line 732, in <module>
    main()
  File "/home/jb/workspace/Genie/src/genie/ui/dialogs/../../invert.py", line 42, in main
    inv_ert(inversion_conf, project_conf)
  File "/home/jb/workspace/Genie/src/genie/ui/dialogs/../../invert.py", line 53, in inv_ert
    if not prepare(cut_par, inv_par, project_conf):
  File "/home/jb/workspace/Genie/src/genie/ui/dialogs/../../invert.py", line 695, in prepare
    run_process([meshlabserver_path, "-i", "point_cloud_cut.xyz", "-o", "gallery_mesh.ply", "-m", "sa", "-s", "meshlab_script.mlx"])
  File "/home/jb/workspace/Genie/src/genie/ui/dialogs/../../invert.py", line 657, in run_process
    p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, universal_newlines=True)
  File "/home/jb/miniconda3/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/home/jb/miniconda3/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'meshlabserver': 'meshlabserver'
```

**Comment by radeksrb** [comment]
2.
data_log má význam že se pro data použije logaritmická transformace
    tM = pg.RTransLogLU()
    if inv_par.data_log:
        tD = pg.RTransLog()
        inv.setTransData(tD)
    inv.setTransModel(tM)
má tedy být vždy True a volbu zrušit?

k_ones neni potreba, bylo pouze pro testovaci učely, takže zruším

optimizeLambda bude tedy implicitně zaskrtnuto, volba bude ponechána

3.
viz dokumentace Installation/Linux/download Meshlab

**Comment by jbrezmorf** [comment]
OK. presunuto do #12
